spring:
  quartz:
    job-store-type: jdbc
    overwriteExistingJobs: true
    properties:
      org.quartz.threadPool.threadCount: 1
  datasource:
    druid:
      url: jdbc:mysql://10.211.55.3:3306/quartz?useUnicode=true&characterEncoding=utf-8
      username: ming
      password: hM123!@#